website/views.py
from crypt import methods
import datetime
from itertools import count
from flask import Blueprint, Flask, render_template, request, session, redirect, url_for, flash
from flask_pymongo import PyMongo
import certifi

views = Blueprint('views', __name__)

# PyMongo ---------------------------------------------------------------------
app = Flask(__name__)
app.config['MONGO_URI'] = "mongodb+srv://GianITS:ProjectITS33@clusterits.do6lt.mongodb.net/Agenzia_Immo?retryWrites=true&w=majority"
mongo = PyMongo(app, tlsCAFile=certifi.where())

@views.route('/HomePage')
def home():
    form0=FormSearch()
    date = datetime.datetime.now()
    date=date.strftime("%A %d %B %Y")
    return render_template('homepage.html', date=date , form0=form0)

@views.context_processor
def base():
    form0 = FormSearch()
    return dict(form0=form0)

# importo i moduli relativi al form
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, RadioField, MultipleFileField, SelectField, TextAreaField, EmailField
from wtforms.validators import DataRequired, InputRequired
from .models import properties_collection, clients_collection
import re

class FormSearch(FlaskForm):
    testo = StringField("", [DataRequired()])
    submit = SubmitField("")

@views.route('/HomePage', methods=['GET','POST'])
def search():
    testo = ""
    form0 = FormSearch()
    if form0.validate_on_submit():
        testo = form0.testo.data
        resCN = list(clients_collection.find({"nome": {"$regex" : testo}}, {"nome":1,"cognome":1,"_id":0}))[::-1]
        resCC = list(clients_collection.find({"cognome": {"$regex" : testo}}, {"nome":1,"cognome":1,"_id":0}))[::-1]
        resI = list(properties_collection.find({"indirizzo": {"$regex" : testo}}, {"nome":1,"cognome":1,"indirizzo":1,"_id":0}))[::-1]
        if len(resCN) + len(resCC) + len(resI) > 1:
            return render_template("search_results.html", resCN=resCN, resCC=resCC, resI=resI)
        if resCN or resCC:
            res = resCN[0]['nome']
            return redirect(url_for("views.ClientPage", nome=res))
        elif resI:
            res = resI[0]['nome']
            return redirect(url_for("views.PropPage", nome=res))
        else:
            flash("Nessun risultato trovato")

    form0.testo.data = ""
    return redirect(url_for("views.home"))

@views.route('/Risultati_della_ricerca', methods=['GET','POST'])
def searchResults(resCN, resCC, resI):
    return render_template("search_results.html", resCN=resCN, resCC=resCC, resI=resI)

#funzione rimuovi document dal db

@views.route('/Clienti/<nome>', methods=['GET','POST'])
def removeC(nome):
    query = clients_collection.find_one_and_delete({"nome":nome})
    if query:
        flash("Cliente rimosso con successo", 'success')
    else:
        flash("Cliente non trovato", 'error')
    return redirect(url_for('views.clients'))

@views.route('/Immobili/<nome>', methods=['GET','POST'])
def removeP(nome):
    query = properties_collection.find_one_and_delete({"nome":nome})
    if query:
        flash("Immobile rimosso con successo", 'success')
    else:
        flash("Immobile non trovato", 'error')
    return redirect(url_for('views.properties'))

# pagina inserimento cliente

class FormInsertClient(FlaskForm):
    nome = StringField("Nome:", [DataRequired()])
    cognome = StringField("Cognome:", [DataRequired()])
    indirizzo = StringField("Indirizzo:", [DataRequired()])
    citta = StringField("citta:", [DataRequired()])
    cellulare = IntegerField("Cellulare:", [DataRequired()])
    mail = EmailField("Email:", [DataRequired()])
    azione = RadioField("Compra/Vende:", validators=[InputRequired()], choices = [("Compra", "Compra"), ("Vende", "Vende")])
    agent = StringField("Agente:")
    submit = SubmitField("Inserisci")

@views.route('/Inserimento_Clienti', methods=["GET", "POST"])
def insert_clients():
    nome = ""
    cognome = ""
    indirizzo = ""
    citta = ""
    cellulare = ""
    mail = ""
    azione =""
    agent = session['agent']

    form0=FormSearch()
    form=FormInsertClient()
    if form.validate_on_submit():
        nome = form.nome.data
        cognome = form.cognome.data
        indirizzo = form.indirizzo.data
        citta = form.citta.data
        cellulare = form.cellulare.data
        mail = form.mail.data
        azione = form.azione.data

        new_client = {"nome":nome, "cognome":cognome, "indirizzo":indirizzo, "citta":citta, "cell":cellulare, "mail":mail, "buysellrent":azione, "agente":agent}

        if clients_collection.find_one({"cellulare":cellulare},{}):
            flash("Numero di telefono utilizzato da un altro cliente", 'error')
        elif clients_collection.find_one({"mail":mail},{}):
            flash("Mail utilizzata da un altro cliente", 'error')
        else:
            clients_collection.insert_one(new_client)
            flash("Cliente aggiunto con successo", 'success')
            return redirect(url_for("views.clients"))
        
    form.nome.data = ""
    form.cognome.data = ""
    form.indirizzo.data = ""
    form.citta.data = ""
    form.cellulare.data = 0
    form.mail.data = ""
    form.azione.data = ""
    return render_template('insert_clients.html', form=form, nome=nome, cognome=cognome, indirizzo=azione, citta=citta, cellulare=cellulare, mail=mail, azione=azione, agent=agent, form0=form0)

# pagina clienti totali

listHeadClient = ["Nome", "Cognome", "Telefono", "E-mail", "Compra\nAffitta", "Agente"]
@views.route('/Clienti')
def clients():
    clienti = list(clients_collection.find({},{"_id":0}))[::-1]
    return render_template('clients.html', clienti=clienti, listHeadClient=listHeadClient)
    
# pagina singolo cliente

@views.route('/PaginaCliente/<nome>')
def ClientPage(nome):
    client = clients_collection.find_one({"nome": nome}, {"_id":0})
    client =list(client.values())
    cognome = client[1]
    indirizzo = client[2]
    citta = client[3]
    cellulare = client[4]
    mail = client[5]
    azione = client[6]
    if client.__len__() == 9: 
        immobile = list(client[8].values())
        indirizzo2 = immobile[0]
        citta2 = immobile[1]
        vendAff = immobile[3]
        mQuadri = immobile[4]
        totStanze = immobile[5]
        string = ""
    else:
        string = "Nessun immobile collegato"
        indirizzo2 = ""
        citta2 = ""
        vendAff = ""
        mQuadri = ""
        totStanze = ""
    return render_template('clients_page.html', nome=nome, cognome=cognome, indirizzo=indirizzo, citta=citta, cellulare=cellulare, mail=mail, azione=azione, indirizzo2=indirizzo2, citta2=citta2, vendAff=vendAff, mQuadri=mQuadri, numStanze=totStanze, string=string)

# pagina immobili totali

listHead = ["Nome", "Cognome", "Indirizzo", "Citta", "Tipologia", "Vendita\nAffitto", "Metri\nquadri", "Agente"]
@views.route('/Immobili')
def properties():
    immobili = list(properties_collection.find({},{"_id":0}))[::-1]
    return render_template('properties.html', immobili=immobili, listHead=listHead)

# recupero le immagini dal db
# import
import gridfs
from urllib import response
from .models import db

@views.route('/image/<filename>')
def image(filename):
    fs = gridfs.GridFS(db)
    gridout = fs.get_last_version(filename=filename)
    response.content_type = 'image/jpeg'
    return gridout.read()

#creo la classe form dell inserimento degli immobili

#  inserire tipologia immobile:
# (appartamento/casa indipendente/casa semindipendente/villa a schiera/rustico)
class FormInsertProperties(FlaskForm):
    owner = StringField("Proprietario:")
    ownerName = StringField("Nome:", validators=[DataRequired()])
    ownerLastname = StringField("Cognome:", validators=[DataRequired()])
    address = StringField("Indirizzo:", validators=[DataRequired()])
    city = StringField("Citta:", validators=[DataRequired()])
    tipologia = SelectField(u"Tipologia:", choices=[('Appartamento', 'Appartamento'),('Casa indipendente','Casa indipendente'),('Casa semindipendente','Casa semindipendente'),('Villa a schiera','Villa a schiera'),('Rustico','Rustico')])
    vendAff = RadioField("Vendita/Affitto:", validators=[InputRequired()], choices=[('Vendita','Vendita'),('Affitto','Affitto')])
    sqMeters = IntegerField("Dimensioni:", validators=[DataRequired()])
    totRoom = IntegerField("Totale stanze:", validators=[DataRequired()])
    description = TextAreaField("Descrizione:", validators=[DataRequired()])
    images = MultipleFileField("Carica immagini:")
    agent = StringField("Agente:")
    submit = SubmitField("Inserisci")

@views.route('/Inserimento_Immobili/<ownerName><ownerLastname>', methods=["GET","POST"])
def insert_properties(ownerName, ownerLastname):
    # resetto tutte le variabili
    # assegno la variabile agente col nome dell agente loggato
    # assegno alla variabile form il form che ho appena creato
    form = FormInsertProperties()
    # form.ownerName.data = ownerName
    # form.ownerLastname.data = ownerLastname
    # print(ownerName)
    
    address = ""
    city = ""
    tipologia = ""
    vendAff = ""
    sqMeters = ""
    totRoom = ""
    description = ""
    images = ""
    agent = session['agent']

    if form.validate_on_submit():
        ownerName = form.ownerName.data
        ownerLastname = form.ownerLastname.data
        address = form.address.data
        city = form.city.data
        tipologia = form.tipologia.data
        vendAff = form.vendAff.data
        sqMeters = form.sqMeters.data
        totRoom = form.totRoom.data
        description = form.description.data
        images = request.files.getlist('images')
        listImg = []
        for image in images:
            mongo.save_file(image.filename, image)
            listImg.append(image.filename)
        post1 = {"indirizzo":address, "citta":city, "tipologia":tipologia, "vendAff":vendAff, "dimensioni":sqMeters, "totroom": totRoom, "textbox":description, "immagini": listImg, "agente":agent}

website/templates/add_imm.html
{% extends "base.html" %}
{% block title %}nuovo immobili{% endblock %}
{% block content %}

<form method="POST">
    <h3 align="center">Nuovo immobile</h3>
    <div class="form-group">
        <label for="address">Address</label>
        <input
          type="text"
          id="address"
          name="address"
          placeholder="Enter Address"
        />
    </div>
    <div class="form-group">
      <label for="city">city</label>
      <input
        type="text"
        id="city"
        name="city"
        placeholder="Enter city"
      />
    </div>
    <div class="form-group">
      <label for="proprietario">proprietario</label>
      <input
        type="text"
        id="proprietario"
        name="proprietario"
        placeholder="Enter proprietario"
      />
    </div>
    <div class="form-group">
      <label for="m^2">grandezza in m^2</label>
      <input
        type="number"
        id="m^2"
        name="m^2"
        placeholder="Enter m^2"
      />
    </div>
    <br />
    <button type="submit" class="button" href="/newImmobile">Submit</button>
  </form>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;600;800;900&display=swap" rel="stylesheet">

    <link rel="icon" href="{{ url_for('static', filename='images/logo.png')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">

    <link rel="stylesheet" 
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      
    <title>CasaSubito - {% block title%} {% endblock title %}</title>
</head>
<body class="bodyBase">
    <div class="header">
        <div class="logo">
            <a href="/HomePage"><img src="{{ url_for('static', filename='/images/logo.png')}}" alt=""><p>CasaSubito</p></a></div>
        <div class="search">
            <form action="" method="post">
                {{form0.hidden_tag()}}
                {{form0.testo.label()}}{{form0.testo(id_="search",placeholder="Cerca...")}}{{form0.submit(class_="icon")}}
            </form>
            <!-- <input type="search" name="search" id="search" placeholder="Cerca..."> -->
            <!-- <div class="icon"></div> -->
        </div>
        <div class="logout">
            <p>{{ session["agent"] }}</p>
            {% if session['agent'] == "Imran" %}
                <div class="user one">
            {% elif session['agent'] == "Gianluca" %}
                <div class="user two">
            {% elif session['agent'] == "Elena" %}
                <div class="user three">
            {% elif session['agent'] == "Luca" %}
                <div class="user four">
            {% elif session['agent'] == "Lorraine" %}
                <div class="user five">
            {% endif %}
                <div class="btnUser"></div>
                <div class="userMenu">
                    <ul>
                        <li>
                            {% if session['agent'] == "Imran" %}
                            <span class="userico one">
                                I
                            </span>
                            {% elif session['agent'] == "Gianluca" %}
                            <span class="userico two">
                                G
                            </span>
                            {% elif session['agent'] == "Elena" %}
                            <span class="userico three">
                                E
                            </span>
                            {% elif session['agent'] == "Luca" %}
                            <span class="userico four">
                                L
                            </span>
                            {% elif session['agent'] == "Lorraine" %}
                            <span class="userico five">
                                L
                            </span>
                            {% endif %}
                            Profilo
                        </li>
                        <li><span class="iconLogout"></span><a href="/">Esci</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="main">
        <div class="menu" id="menu">
            <div class="contUp">
                <a href="/Clienti">CLIENTI</a>
                <a href="/Immobili">IMMOBILI</a>
            </div>
            <div class="contDown">
                <div class="btninsert" id="btninsert"></div>
                <div class="dpList" id="dpList">
                    <div class="innerIns">
                        <a href="/Inserimento_Clienti" class="btninsert one"></a><span class="spanIns1">Cliente</span>
                    </div>
                    <div class="innerIns">
                        <a href="{{ url_for('views.insert_properties', ownerName=' ', ownerLastname=' ') }}" class="btninsert two"></a><span class="spanIns2">Immobile</span>
                    </div>
                </div>
            </div>
        </div>
        {% block content %}
        {% endblock content %}
    </div>

    <script src="{{ url_for('static', filename='app.js')}}"></script>
    <script src="{{ url_for('static', filename='image.js')}}"></script>
</body>
</html>

website/templates/client.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}Home Page{% endblock %}

website/templates/clients.html
{% extends 'base.html' %}
{% block title %} Clienti {% endblock title %}
{% block content %}
<div class="mainProp">
    <h1 class="">Clienti</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'success' %}
                    <div class="message">
                        {{ message }}
                    </div>
                {% else %}
                    <div class="message error">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <table class="tbProp">
        <thead>
        <tr>
            <th class="open th"></th>
            {% for x in listHeadClient %}
                <th>{{ x }}</th>
            {% endfor %}
            <th class="remove th"></th>
        </tr>
        </thead>
        <tbody>
        {% for cliente in clienti %}
            <tr>
                <td class="open"><a href="{{url_for('views.ClientPage', nome=cliente['nome'])}}"></a></td>
                {% for k,v in cliente.items() %}
                    {% if k != "Immobili" and k != "indirizzo" and k != "citta" and k != "immobili" %}
                        <td>{{ v }}</td>
                    {% endif %}
                {% endfor %}
                <td class="remove"><a href="{{url_for('views.removeC', nome=cliente['nome'])}}"></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

website/templates/clients_page.html
{% extends 'base.html' %}
{% block title %} Dettaglio cliente {% endblock title %}
{% block content %}
    <div class="mainSingle">
        <a href="{{url_for('views.clients')}}" class="btnBack"><div class="ico"></div></a>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div class="message">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <div class="container2">
            <div class="content1">
                <h1 style="text-align:center; color:white">Cliente</h1>
                <center>
                    <table>
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <td class="linea">{{nome}}</td>
                                <th>Cognome</th>
                                <td class="linea">{{cognome}}</td>
                                <th>Città</th>
                                <td class="linea">{{citta}}</td>                    
                            </tr>
                            <tr>
                                <th>Indirizzo</th>
                                <td class="linea">{{indirizzo}}</td>
                                <th>Cellulare</th>
                                <td class="linea">{{cellulare}}</td>
                                <th>E-mail</th>
                                <td class="linea">{{mail}}</td>
                            </tr>
                            <tr>
                                <th>Stato Immobile</th>
                                <td class="linea">{{azione}}</td>
                                <td></td>
                                <td></td>
                                <th>Agente</th>
                                <td class="linea">{{ session['agent'] }}</td>
                            </tr>
                        </thead>
                    </table>
                </center>
            </div>
            <div class="content2">
                <h2 style="text-align:center;">Immobile</h2>
                <center>
                    <table>
                        <thead>
                            {% if string == "" %}
                            <a href="{{url_for('views.PropPage', nome=nome)}}" class="btnRedirect"><div class="icona"></div></a>
                                <tr>
                                    <th>Proprietario</th>
                                    <td class="linea">{{nome}}</td>
                                    <th>Città</th>
                                    <td class="linea">{{citta2}}</td>
                                    <th>Indirizzo</th>
                                    <td class="linea">{{indirizzo2}}</td>                    
                                </tr>
                                <tr>
                                    <th>Metri<br>Quadri</th>
                                    <td class="linea">{{mQuadri}}</td>
                                    <th>Numero<br>Stanze</th>
                                    <td class="linea">{{numStanze}}</td>
                                    <th>Stato<br>Immobile</th>
                                    <td class="linea">{{vendAff}}</td>
                                </tr>
                                {% else %}
                                <tr>
                                    <a href="{{url_for('views.insert_properties', ownerName=nome, ownerLastname=cognome)}}" class="btnNewImmo">Nuovo</a>
                                    <h2 class="newH2">{{ string }}</h2>
                                </tr>
                            {% endif %}
                        </thead>
                    </table>
                </center>
            </div>
            <div class="content3">
                <div class="up">
                    <h2>Richieste Immobiliari</h2>
                    <span class="iconExtend" id="btnEx"></span>
                </div>
                <p>Nessuna richiesta inserita</p>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<form action="">
    <a class="button" id="logout" href="/add_immobile">+</a>
</form>
{% endblock %}

website/templates/immobili.html
{% extends "base.html" %}
{% block title %}miei immobili{% endblock %}
{% block content %}
<p><h1>Miei immobili</h1></p>

<!-- 
<ul class="list" id="immobili">
    {% for immobile in clt.immobili %}
    <li class="list">
        {{ immobile }}
    </li>
    {% endfor %}
</ul>
-->

{% endblock %}

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="{{ url_for('static', filename='images/logo.png')}}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;600;800;900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quattrocento+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
    <title>Login CasaSubito</title>
</head>
<body class="bodyLog">
    <img src="../static/images/logo.png" alt="">
    <!-- <h1>CasaSubito</h1> -->
    <h2>Accedi</h2>
    <form action="" method="post" id="form" enctype="multipart/form-data">
        {{form.hidden_tag()}}
        <div class="utente">
            {{form.utente.label(class_="utente")}}
            {{form.utente( class_="large",placeholder="Username...")}}
        </div>
        <div class="password" >
            {{form.password.label(class_="password")}}
            {{form.password(class_="large", placeholder="Password...")}}
        </div>
        {{form.submit(class_="btnSub")}}
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="message">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
    </form>
</body>
</html>

website/templates/properties.html
{% extends 'base.html' %}
{% block title %} Immobili {% endblock title %}
{% block content %}
<div class="mainProp">
    <h1>Immobili</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="message">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <table class="tbProp">
        <thead>
            <tr>
                <th class="open th"></th>
                {% for item in listHead %}
                    <th>{{ item }}</th>
                {% endfor %}
                <th class="remove th"></th>
            </tr>
        </thead>
        <tbody>
            {% for immobile in immobili %}
            <tr>
                <td class="open"><a href="{{url_for('views.PropPage', nome=immobile['nome'])}}"></a></td>
                {% for k,v in immobile.items() %}
                    {% if loop.index == 1 %}
                        <td><a href="{{url_for('views.ClientPage', nome=immobile['nome'])}}">{{ v }}</a></td>
                    {% elif k != "immagini" and k != "descrizione" and k != "textbox" and k != "dimensioni" %}
                        <td>{{ v }}</td>
                    {% endif %}
                {% endfor %}
                <td class="remove"><a href="{{url_for('views.removeP', nome=immobile['nome'])}}"></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% block PropPage %}
    {% endblock %}
</div>
{% endblock content %}

website/templates/property_page.html
{% extends 'base.html' %}
{% block title %} Dettaglio immobile {% endblock title %}
{% block content %}
    <div class="mainSingle">
        <a href="{{url_for('views.properties')}}" class="btnBack"><div class="ico"></div></a>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="message">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <div class="container2">
            <div class="content1">
                <h1 style="text-align:center; color:white">Immobile</h1>
                <center>
                    <table>
                        <thead>
                            <tr>
                                <th>Prorietario</th>
                                <td class="linea">{{nome}}</td>
                                <th>Città</th>
                                <td class="linea">{{citta}}</td>
                                <th>Indirizzo</th>
                                <td class="linea">{{indirizzo}}</td>
                                <th>Metri<br>Quadri</th>
                                <td class="linea">{{mQuadri}}</td>
                                                                    
                            </tr>
                                
                                <th>Numero<br>Stanze</th>
                                <td class="linea">{{numStanze}}</td>
                                <th>Stato<br>Immobile</th>
                                <td class="linea">{{vendAff}}</td>
                                <th>Descrizione</th>
                                <td class="linea colLong" rowspan="2">{{descrizione}}</td> 
                            </tr>
                                <th>Agente</th>
                                <td class="linea">{{ session['agent'] }}</td>
                                <td></td>
                                <td class="clickImmagine"><a href="{{url_for('views.showImg', nome=nome)}}"><span class="material-symbols-outlined">
                                    photo_library
                                    </span></a>
                                </td>
                            </tr>
                        </thead>
                    </table>
                </center>
            </div>
            <div class="content2 long">
                <a href="{{url_for('views.ClientPage', nome=nome)}}" class="btnRedirect"><div class="icona"></div></a>
                <h2 style="text-align:center;">Cliente</h2>
                <center>
                    <table>
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <td class="linea">{{nome}}</td>
                                <th>Cognome</th>
                                <td class="linea">{{cognome}}</td>
                                <th>Città</th>
                                <td class="linea">{{citta2}}</td>
                                                
                            <!-- </tr>
                                <th>Indirizzo</th>
                                <td class="linea">{{indirizzo2}}</td> 
                                <th>Cellulare</th>
                                <td class="linea">{{cellulare}}</td>
                                <th>E-mail</th>
                                <td class="linea">{{mail}}</td>
                           </tr> -->
                        </thead>
                    </table>
                </center>
             </div>
             <div class="content3 long">
             <center>
                 <div class="maps">
                     <h2>Ubicazione</h2>
                     <div class="imgGoogle"></div>
                 </div>
            </center>
            </div>
        </div>

        {% block PropPage %}
        {% endblock %}
    </div>
{% endblock %}

website/templates/show_img.html
{% extends 'property_page.html' %}
{% block PropPage %}
<div class="section">
    <div class="container showImg">
        <a href="{{url_for('views.PropPage', nome=nome)}}" class="btnclose"></a>
        <div class="slider">
            {% for image in listImg %}
            {% set j=loop.index %}
                <div class="slides s{{j}}">
                    <img src="{{url_for('views.image', filename=image)}}" alt="">
                </div>
            {% endfor %}
        </div>
        <div class="carousel">
            {% for image in listImg %}
                {% set i=loop.index %}
                <div class="innerCar">
                    {% if i==1 %}
                        <input type="radio" name="carousel" id="inner{{i}}" checked>
                        
                    {% else %}
                        <input type="radio" name="carousel" id="inner{{i}}">
                    {% endif %}
                    <img src="{{url_for('views.image', filename=image)}}" alt="">
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

website/templates/user.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
<form action=ìì>
    <a class="button" id="logout" href="/logout">logout</a>
</form>
{% endblock %}